{
  "da": "Botten mislykkedes med at genforbinde til DeepL API-serverne.",
  "de": "Der Bot konnte keine Verbindung zu den DeepL API-Servern herstellen.",
  "en-GB": "The bot failed to reconnect to the DeepL API servers.",
  "en-US": "The bot failed to reconnect to the DeepL API servers.",
  "es-ES": "El bot no pudo reconectarse a los servidores de la API de DeepL.",
  "fr": "Le bot n'a pas réussi à se reconnecter aux serveurs de l'API DeepL.",
  "hr": "Botu nije uspjelo ponovno se povezati na DeepL API poslužitelje.",
  "it": "Il bot non è riuscito a riconnettersi ai server API di DeepL.",
  "lt": "Botui nepavyko iš naujo prisijungti prie „DeepL“ API serverių.",
  "hu": "A bot nem tudott újrakapcsolódni a DeepL API szerverekhez.",
  "nl": "De bot kon niet opnieuw verbinding maken met de DeepL API servers.",
  "no": "Botten klarte ikke å gjenopprette forbindelsen til DeepL API-serverne.",
  "pl": "Bot nie zdołał ponownie połączyć się z serwerami API DeepL.",
  "pt-BR": "O bot falhou ao se reconectar aos servidores da API do DeepL.",
  "ro": "Botul nu a reușit să se reconecteze la serverele API DeepL.",
  "fi": "Botti ei onnistunut uudelleenyhdistämään DeepL API -palvelimiin.",
  "sv-SE": "Botten misslyckades med att återansluta till DeepL API-servrarna.",
  "vi": "Bot không thể kết nối lại được với các máy chủ API của DeepL.",
  "tr": "Bot, DeepL API sunucularına yeniden bağlanmayı başaramadı.",
  "cs": "Botu se nepodařilo znovu připojit k serverům DeepL API.",
  "el": "Το bot απέτυχε να επανασυνδεθεί στους διακομιστές API του DeepL.",
  "bg": "Ботът не успя да се свърже отново със сървърите на DeepL API.",
  "ru": "Боту не удалось повторно подключиться к серверам API DeepL.",
  "uk": "Боту не вдалося повторно підключитися до серверів API DeepL.",
  "hi": "बॉट ने DeepL API सर्वरों से पुनः कनेक्ट करने में विफल रहा।",
  "th": "บอทไม่สามารถเชื่อมต่อใหม่กับเซิร์ฟเวอร์ API ของ DeepL ได้",
  "zh-CN": "机器人未能重新连接到DeepL API服务器。",
  "ja": "ボットはDeepL APIサーバへの再接続に失敗しました。",
  "zh-TW": "機器人未能重新連接到DeepL API服務器。",
  "ko": "봇이 DeepL API 서버에 재연결하는 데 실패했습니다."
}